function localSgtitle(str)
% LOCALSGTITLE Add a figure-level title to the current figure.
%   Uses a hidden axes with a text annotation for compatibility with Octave
%   (which does not support sgtitle).
  ax = axes('Position', [0, 0.95, 1, 0.05], 'Visible', 'off');
  text(ax, 0.5, 0.5, str, ...
       'HorizontalAlignment', 'center', ...
       'VerticalAlignment', 'middle', ...
       'FontWeight', 'bold', ...
       'FontSize', 11);
end
