/**
 * @file RteTypesGenerated.h
 * @brief Autogenerated declarations of SWC port data types.
 *
 * THIS FILE WAS AUTOMATICALLY GENERATED FROM
 * A TEMPLATE AND A JSON CONFIGURATION FILE
 *
 * @date {DATE_GENERATED}
 */

#ifndef RTE_TYPES_GENERATED_H
#define RTE_TYPES_GENERATED_H

#ifndef __cplusplus
  #error This header must not be included in .c files.
#endif /* __cplusplus */

#include "DataSerializer.h"
#include "CSerializable.h"
#include "UintToBool.h"


// ----IMPORTANT----
//
// Port data can be sent as a part of debug output. Therefore it is
// required to ensure that the port data types below do not use
// any implementation defined types. The type bool is implementation
// defined and its size will not be the same on different platforms.
// This is why we will use uint8_t for logical data in software
// component ports.
//
// ----IMPORTANT----

{DECLARATION_OF_PORT_DATA_TYPES}

#endif /* RTE_TYPES_GENERATED_H */
