/// @file CLis3mdlDriver.h
/// @brief Implementation of the LIS3MDL driver software component class.
/// @copyright Copyright 2025. AMS Advanced Air Mobility Sensors UG. All rights reserved.

// Datasheet: DS9463 - Rev 7 - December 2023

#ifndef C_LIS3MDL_DRIVER_H
#define C_LIS3MDL_DRIVER_H

#include "General/CSoftwareComponentBase.h"


class CLis3mdlDriver : public CSoftwareComponent<CLis3mdlDriver, 1U>
{
  friend class CSoftwareComponent<CLis3mdlDriver, 1U>;
  FORBID_CLASS_COPY_AND_MOVE(CLis3mdlDriver)
  DECLARE_MANDATORY_APIS(CLis3mdlDriver)

public:
  /// @brief Poll the LIS3MDL sensor.
  /// @param uTimestamp Timestamp of the measurement generated by data-ready interrupt handler.
  void PollSensor(uint64_t uTimestamp);

  /// @brief A function overload that generates a timestamp without a data-ready interrupt.
  void PollSensor();

private:
  CLis3mdlDriver() = default;
  ~CLis3mdlDriver() = default;

  static constexpr uint16_t skuLis3mdlI2CAddress_{ 0x001E << 1U }; // SAD+R/W

  static constexpr uint8_t skuLis3mdlRegWhoAmI_{ 0x0F };
  static constexpr uint8_t skuLis3mdlRegCtrlReg1_{ 0x20 };
  static constexpr uint8_t skuLis3mdlRegCtrlReg2_{ 0x21 };
  static constexpr uint8_t skuLis3mdlRegCtrlReg3_{ 0x22 };
  static constexpr uint8_t skuLis3mdlRegCtrlReg4_{ 0x23 };
  static constexpr uint8_t skuLis3mdlRegCtrlReg5_{ 0x24 };
  static constexpr uint8_t skuLis3mdlRegStatReg_{ 0x27 };
  static constexpr uint8_t skuLis3mdlRegOutXL_{ 0x28 };
  static constexpr uint8_t skuLis3mdlRegTempOutL_{ 0x2e };

  static constexpr uint8_t skuLis3mdlWhoAmI_{ 0x3D };

  // CTRL_REG1 (20h)
  static constexpr uint8_t skuLis3mdlCtrlReg1TempEn_{ 0x01 << 7U }; // 1: temperature sensor enabled
  static constexpr uint8_t skuLis3mdlCtrlReg1OpModeXY_{ 0x03 << 5U }; // X and Y axes ultrahigh-performance mode
  static constexpr uint8_t skuLis3mdlCtrlReg1Odr_{ 0x04 << 2U }; // ODR 10 Hz

  static constexpr uint8_t skuLis3mdlCtrlReg1Value_{ skuLis3mdlCtrlReg1TempEn_ | skuLis3mdlCtrlReg1OpModeXY_ | skuLis3mdlCtrlReg1Odr_ };

  // CTRL_REG3 (22h)
  static constexpr uint8_t skuLis3mdlCtrlReg3Value_{ 0x00 }; // No Low-power mode, Continuous-conversion mode
  // CTRL_REG4 (23h)
  static constexpr uint8_t skuLis3mdlCtrlReg4OpModeZ_{ 0x03 << 2U }; // Z axis ultrahigh-performance mode

  // STATUS_REG (27h)
  static constexpr uint8_t skuLis3mdlStatRegXYZDataReady_{ 0x01 << 3U }; // X-, Y- and Z-axis new data available

  // Magnetic measuremnet
  static constexpr float skfLis3mdlMagneticSensitivity_{ (1.0F / 6842.0F) }; // Table 2: Magnetic sensitivity @ FS = ±4 gauss
  // Temperature
  static constexpr float skfLis3mdlTempSensitivity_{ (1.0F / 8.0F) }; // Table 3: Temperature sensitivity

  // I2C timeout
  static constexpr uint32_t skuLis3mdlI2cTimeout_{2U};

  bool getDeviceId(uint8_t& urChipId);

  bool readMagnetometer(float& frValueX, float& frValueY, float& frValueZ);
  bool readTemperature(float& frTemperature);

  bool isDataReady();

  bool readReg(uint8_t uRegAddr, uint8_t* upBuffer, uint16_t uLen);
  bool writeReg(uint8_t uRegAddr, const uint8_t* upBuffer, uint16_t uLen);

  bool bIsInitialized_{ false };  ///< Sensor status after initialization

};

#endif /* C_LIS3MDL_DRIVER_H */
