/**
 * @file RteTypesGenerated.h
 * @brief Autogenerated declarations of SWC port data types.
 *
 * THIS FILE WAS AUTOMATICALLY GENERATED FROM
 * A TEMPLATE AND A JSON CONFIGURATION FILE
 *
 * @date 29.05.2026 at 10:43:47
 */

#ifndef RTE_TYPES_GENERATED_H
#define RTE_TYPES_GENERATED_H

#ifndef __cplusplus
  #error This header must not be included in .c files.
#endif /* __cplusplus */

#include "DataSerializer.h"
#include "CSerializable.h"
#include "UintToBool.h"


// ----IMPORTANT----
//
// Port data can be sent as a part of debug output. Therefore it is
// required to ensure that the port data types below do not use
// any implementation defined types. The type bool is implementation
// defined and its size will not be the same on different platforms.
// This is why we will use uint8_t for logical data in software
// component ports.
//
// ----IMPORTANT----

struct SImuMeasurement final : public NLibCommon::CSerializable
{
  float fSpecificForceX_{ 0.0F }; ///< Specific force X, [m/s^2]
  float fSpecificForceY_{ 0.0F }; ///< Specific force Y, [m/s^2]
  float fSpecificForceZ_{ 0.0F }; ///< Specific force Z, [m/s^2]
  float fAngularRateX_{ 0.0F }; ///< Angular rate X, [rad/s]
  float fAngularRateY_{ 0.0F }; ///< Angular rate Y, [rad/s]
  float fAngularRateZ_{ 0.0F }; ///< Angular rate Z, [rad/s]
  float fTemperature_{ 0.0F }; ///< Temperature in degrees Celsius
  uint64_t uTimestampUs_{ 0U }; ///< Timestamp in microseconds
  uint8_t uImuValid_{ 0U }; ///< Validity flag
  uint8_t uTemperatureValid_{ 0U }; ///< Validity flag

#if defined(SEND_DEBUG_OUTPUT) || defined(_MSC_VER)
  
  std::vector<uint8_t> ToByteVector() final
  {
    std::vector<uint8_t> oBytes;
    bool bStatus =  NLibCommon::Serialize(oBytes, 
      fSpecificForceX_,
      fSpecificForceY_,
      fSpecificForceZ_,
      fAngularRateX_,
      fAngularRateY_,
      fAngularRateZ_,
      fTemperature_,
      uTimestampUs_,
      uImuValid_,
      uTemperatureValid_);
  
    if (false == bStatus)
    {
      oBytes.clear();
    }
  
    return oBytes;
  }
  
  bool FromByteVector(const std::vector<uint8_t>& korBytes) final
  {
    bool bStatus = NLibCommon::Deserialize(korBytes, 
      fSpecificForceX_,
      fSpecificForceY_,
      fSpecificForceZ_,
      fAngularRateX_,
      fAngularRateY_,
      fAngularRateZ_,
      fTemperature_,
      uTimestampUs_,
      uImuValid_,
      uTemperatureValid_);
  
    if (false == bStatus)
    {
      *this = SImuMeasurement();
    }
  
    return bStatus;
  }
#endif /* SEND_DEBUG_OUTPUT || _MSC_VER */
};

struct SAttitudeData final : public NLibCommon::CSerializable
{
  float fRoll_{ 0.0F }; ///< Roll angle, [rad]
  float fPitch_{ 0.0F }; ///< Pitch angle, [rad]
  float fAttitudeStd1_{ 0.0F }; ///< Standard deviation of attitude estimate, [rad]
  float fAttitudeStd2_{ 0.0F }; ///< Standard deviation of attitude estimate, [rad]
  uint64_t uTimestampUs_{ 0U }; ///< Timestamp in microseconds
  uint8_t uValid_{ 0U }; ///< Validity flag

#if defined(SEND_DEBUG_OUTPUT) || defined(_MSC_VER)
  
  std::vector<uint8_t> ToByteVector() final
  {
    std::vector<uint8_t> oBytes;
    bool bStatus =  NLibCommon::Serialize(oBytes, 
      fRoll_,
      fPitch_,
      fAttitudeStd1_,
      fAttitudeStd2_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      oBytes.clear();
    }
  
    return oBytes;
  }
  
  bool FromByteVector(const std::vector<uint8_t>& korBytes) final
  {
    bool bStatus = NLibCommon::Deserialize(korBytes, 
      fRoll_,
      fPitch_,
      fAttitudeStd1_,
      fAttitudeStd2_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      *this = SAttitudeData();
    }
  
    return bStatus;
  }
#endif /* SEND_DEBUG_OUTPUT || _MSC_VER */
};

struct SMagneticHeading final : public NLibCommon::CSerializable
{
  float fMagneticHeading_{ 0.0F }; ///< Magnetic heading, [rad]
  uint64_t uTimestampUs_{ 0U }; ///< Timestamp in microseconds
  uint8_t uValid_{ 0U }; ///< Validity flag

#if defined(SEND_DEBUG_OUTPUT) || defined(_MSC_VER)
  
  std::vector<uint8_t> ToByteVector() final
  {
    std::vector<uint8_t> oBytes;
    bool bStatus =  NLibCommon::Serialize(oBytes, 
      fMagneticHeading_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      oBytes.clear();
    }
  
    return oBytes;
  }
  
  bool FromByteVector(const std::vector<uint8_t>& korBytes) final
  {
    bool bStatus = NLibCommon::Deserialize(korBytes, 
      fMagneticHeading_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      *this = SMagneticHeading();
    }
  
    return bStatus;
  }
#endif /* SEND_DEBUG_OUTPUT || _MSC_VER */
};

struct STimeOfSyncPulse final : public NLibCommon::CSerializable
{
  uint64_t uPulseTimeUs_{ 0U }; ///< Timestamp in microseconds

#if defined(SEND_DEBUG_OUTPUT) || defined(_MSC_VER)
  
  std::vector<uint8_t> ToByteVector() final
  {
    std::vector<uint8_t> oBytes;
    bool bStatus =  NLibCommon::Serialize(oBytes, 
      uPulseTimeUs_);
  
    if (false == bStatus)
    {
      oBytes.clear();
    }
  
    return oBytes;
  }
  
  bool FromByteVector(const std::vector<uint8_t>& korBytes) final
  {
    bool bStatus = NLibCommon::Deserialize(korBytes, 
      uPulseTimeUs_);
  
    if (false == bStatus)
    {
      *this = STimeOfSyncPulse();
    }
  
    return bStatus;
  }
#endif /* SEND_DEBUG_OUTPUT || _MSC_VER */
};

struct SBarometerMeasurement final : public NLibCommon::CSerializable
{
  float fPressure_{ 0.0F }; ///< Pressure in Pascals
  float fTemperature_{ 0.0F }; ///< Temperature in degrees Celsius
  uint64_t uTimestampUs_{ 0U }; ///< Timestamp in microseconds
  uint8_t uValid_{ 0U }; ///< Validity flag

#if defined(SEND_DEBUG_OUTPUT) || defined(_MSC_VER)
  
  std::vector<uint8_t> ToByteVector() final
  {
    std::vector<uint8_t> oBytes;
    bool bStatus =  NLibCommon::Serialize(oBytes, 
      fPressure_,
      fTemperature_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      oBytes.clear();
    }
  
    return oBytes;
  }
  
  bool FromByteVector(const std::vector<uint8_t>& korBytes) final
  {
    bool bStatus = NLibCommon::Deserialize(korBytes, 
      fPressure_,
      fTemperature_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      *this = SBarometerMeasurement();
    }
  
    return bStatus;
  }
#endif /* SEND_DEBUG_OUTPUT || _MSC_VER */
};

struct SMagneticMeasurement final : public NLibCommon::CSerializable
{
  float fVectorX_{ 0.0F }; ///< Magnetic field vector in mG axis X
  float fVectorY_{ 0.0F }; ///< Magnetic field vector in mG axis Y
  float fVectorZ_{ 0.0F }; ///< Magnetic field vector in mG axis Z
  float fTemperature_{ 0.0F }; ///< Temperature in degrees Celsius
  uint64_t uTimestampUs_{ 0U }; ///< Timestamp in microseconds
  uint8_t uValid_{ 0U }; ///< Validity flag

#if defined(SEND_DEBUG_OUTPUT) || defined(_MSC_VER)
  
  std::vector<uint8_t> ToByteVector() final
  {
    std::vector<uint8_t> oBytes;
    bool bStatus =  NLibCommon::Serialize(oBytes, 
      fVectorX_,
      fVectorY_,
      fVectorZ_,
      fTemperature_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      oBytes.clear();
    }
  
    return oBytes;
  }
  
  bool FromByteVector(const std::vector<uint8_t>& korBytes) final
  {
    bool bStatus = NLibCommon::Deserialize(korBytes, 
      fVectorX_,
      fVectorY_,
      fVectorZ_,
      fTemperature_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      *this = SMagneticMeasurement();
    }
  
    return bStatus;
  }
#endif /* SEND_DEBUG_OUTPUT || _MSC_VER */
};

struct SVerticalChannelData final : public NLibCommon::CSerializable
{
  float fHeight_{ 0.0F }; ///< Height, [m]
  float fVelocityDown_{ 0.0F }; ///< Vertical velocity (positive downwards), [m/s]
  uint64_t uTimestampUs_{ 0U }; ///< Timestamp in microseconds
  uint8_t uValid_{ 0U }; ///< Validity flag

#if defined(SEND_DEBUG_OUTPUT) || defined(_MSC_VER)
  
  std::vector<uint8_t> ToByteVector() final
  {
    std::vector<uint8_t> oBytes;
    bool bStatus =  NLibCommon::Serialize(oBytes, 
      fHeight_,
      fVelocityDown_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      oBytes.clear();
    }
  
    return oBytes;
  }
  
  bool FromByteVector(const std::vector<uint8_t>& korBytes) final
  {
    bool bStatus = NLibCommon::Deserialize(korBytes, 
      fHeight_,
      fVelocityDown_,
      uTimestampUs_,
      uValid_);
  
    if (false == bStatus)
    {
      *this = SVerticalChannelData();
    }
  
    return bStatus;
  }
#endif /* SEND_DEBUG_OUTPUT || _MSC_VER */
};



#endif /* RTE_TYPES_GENERATED_H */
